import js from "@eslint/js";
import pluginVue from "eslint-plugin-vue";
import tseslint from "typescript-eslint";

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  {
    files: ["**/*.{js,ts,vue}"],
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        URL: "readonly",
        Blob: "readonly",
        Intl: "readonly",
        speechSynthesis: "readonly",
        RTCPeerConnection: "readonly",
        OfflineAudioContext: "readonly",
        AudioContext: "readonly",
        screen: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        Date: "readonly",
        Set: "readonly",
        Map: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Object: "readonly",
        Array: "readonly",
        Error: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Symbol: "readonly",
        isNaN: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        encodeURIComponent: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        performance: "readonly",
        WebGL2RenderingContext: "readonly",
        WebGLRenderingContext: "readonly",
        AbortController: "readonly",
        MediaRecorder: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
        atob: "readonly",
        btoa: "readonly",
        File: "readonly",
        FileReader: "readonly",
        XMLHttpRequest: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        Location: "readonly",
        History: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        HTMLElement: "readonly",
        HTMLCanvasElement: "readonly",
        CanvasRenderingContext2D: "readonly",
        Image: "readonly",
        ImageData: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        ServiceWorker: "readonly",
        Notification: "readonly",
        Permissions: "readonly",
        PermissionStatus: "readonly",
        ResizeObserver: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
      },
    },
    rules: {
      // Disable some rules that are too strict for this project
      "vue/multi-word-component-names": "off",
      "vue/no-v-html": "off",
      "vue/max-attributes-per-line": "off",
      "vue/singleline-html-element-content-newline": "off",
      "vue/multiline-html-element-content-newline": "off",
      "vue/html-self-closing": "off",
      "vue/attributes-order": "off",
      "vue/html-indent": "off",
      "vue/attribute-hyphenation": "off",
      "vue/html-closing-bracket-newline": "off",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_?", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-empty": ["error", { "allowEmptyCatch": true }],
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", "*.config.js"],
  },
];
